### ISSUE TITLE
CSS grid layout & fallback flexbox

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/CSS3#10]
# CSS grid layout & fallback flexbox

https://zellwk.com/blog/calendar-flexbox-fallback/

## `@supports`

> 特征检测, flexbox 渐进增强(grid  优雅降级)

https://developer.mozilla.org/en-US/docs/Web/CSS/@supports

![](https://img2018.cnblogs.com/blog/740516/201912/740516-20191201214054908-1712272957.png)

https://caniuse.com/#search=@supports

![](https://img2018.cnblogs.com/blog/740516/201912/740516-20191201213754480-189546884.png)

```css


/*  flexbox 渐进增强 */

.day-of-week,
.date-grid {
  display: flex;
}

/* grid  优雅降级 */

@supports (display: grid) {
  .day-of-week,
  .date-grid {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
  }

  .date-grid button:first-child {
    grid-column: 6;
  }
}

```
