### ISSUE TITLE
grid layout

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/CSS3#13]
# css grid layout in practice

https://caniuse.com/#search=grid

![](https://img2018.cnblogs.com/blog/740516/201912/740516-20191201210807533-605308991.png)

> subgrid

![](https://img2018.cnblogs.com/blog/740516/201912/740516-20191201211055980-996323402.png)

https://caniuse.com/#search=calc

![](https://img2018.cnblogs.com/blog/740516/201912/740516-20191201212939170-120866478.png)

## tutorials

https://css-tricks.com/snippets/css/complete-guide-grid/

![](https://img2018.cnblogs.com/blog/740516/201912/740516-20191203194453412-1640719388.png)

![](https://img2018.cnblogs.com/blog/740516/201912/740516-20191203194355676-1077242840.png)

## grid & animation

https://codepen.io/xgqfrms/pen/jOEEOWg

```css

```

<iframe height="300" style="width: 100%;" scrolling="no" title="CSS Grid Layout: Animation" src="https://codepen.io/xgqfrms/embed/jOEEOWg?height=300&theme-id=25577&default-tab=html,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/xgqfrms/pen/jOEEOWg'>CSS Grid Layout: Animation</a> by xgqfrms
  (<a href='https://codepen.io/xgqfrms'>@xgqfrms</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>

## grid & function

https://css-tricks.com/snippets/css/complete-guide-grid/#article-header-id-4

![](https://img2018.cnblogs.com/blog/740516/201912/740516-20191203204423458-816907444.png)

https://codepen.io/xgqfrms/pen/JjoojYN

```css

```

<iframe height="300" style="width: 100%;" scrolling="no" title="CodePen Home That Grid Thing Everybody Loves 'Cause It's Awesome" src="https://codepen.io/xgqfrms/embed/JjoojYN?height=300&theme-id=25577&default-tab=html,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/xgqfrms/pen/JjoojYN'>CodePen Home That Grid Thing Everybody Loves 'Cause It's Awesome</a> by xgqfrms
  (<a href='https://codepen.io/xgqfrms'>@xgqfrms</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>

## grid layout

https://codepen.io/webgeeker/pen/GRgRVBZ

```html

<!-- CSS Grid -->
<h1 class="title">CSS GRID</h1>
<div class="wrapper">
    <div class="header">HEADER</div>
    <div class="menu">MENU</div>
    <div class="content">CONTENT</div>
    <div class="footer">FOOTER</div>
</div>

```

```css


.wrapper {
    display: grid;
    grid-template-columns: repeat(12, 1fr);
    /* 水平 12 col 布局 */
    grid-template-rows: 40px 100px 40px;
    /* 垂直，3 row 高度 */
    /* overflow: auto; */
}

.wrapper > div {
    padding-left: 20px;
    color: #ffeead;
    display: flex;
    align-items: center;
    font-size: 20px;
    /* min-width: 200px; */
}

.header {
    grid-column: span 12;
}

.menu {
    grid-column: span 4;
}

.content {
    grid-column: span 8;
}

.footer {
    grid-column: span 12;
}

@media screen and (max-width: 480px) {
    .header {
        grid-column: span 6;
    }
    
    .menu {
        /* 指定所在的 row 为 1 */
        grid-row: 1;
        grid-column: span 6;
    }
    
    .content {
        grid-column: span 12;
    }
}



```

<iframe height="265" style="width: 100%;" scrolling="no" title="css grid layout demo" src="https://codepen.io/webgeeker/embed/GRgRVBZ?height=265&theme-id=default&default-tab=css,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/webgeeker/pen/GRgRVBZ'>css grid layout demo</a> by xgqfrms
  (<a href='https://codepen.io/webgeeker'>@webgeeker</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>

## css grid & fallback

https://www.smashingmagazine.com/2017/11/css-grid-supporting-browsers-without-grid/

https://codepen.io/webgeeker/pen/LYEPqwe

```css

* { box-sizing: border-box; }

body {
  margin: 40px;
  background-color: #fff;
  color: #444;
  font: 1.4em Arial, sans-serif;
}

.grid {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  grid-auto-rows: 100px;
  grid-gap: 20px;
}

.grid > * {
  padding: 10px;
  border: 5px solid rgba(214,129,137,.5);
  border-radius: 5px;
  background-color: rgba(233,78,119,.5);
  color: #fff;
  float: left;  
  width: 33%;
}

@supports (display:grid) {
  .grid > * {
    width: auto;
  }
}


```

https://zellwk.com/blog/calendar-flexbox-fallback/

## `@supports`

> 特征检测, flexbox 渐进增强(grid  优雅降级)

https://developer.mozilla.org/en-US/docs/Web/CSS/@supports

![](https://img2018.cnblogs.com/blog/740516/201912/740516-20191201214054908-1712272957.png)

https://caniuse.com/#search=@supports

![](https://img2018.cnblogs.com/blog/740516/201912/740516-20191201213754480-189546884.png)

```css


/*  flexbox 渐进增强 */

.day-of-week,
.date-grid {
  display: flex;
}

/* grid  优雅降级 */

@supports (display: grid) {
  .day-of-week,
  .date-grid {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
  }

  .date-grid button:first-child {
    grid-column: 6;
  }
}

```

## CSS3 Grid Layout

http://www.csstutorial.org/css-grid-tutorial.html

https://www.cnblogs.com/xgqfrms/p/10771746.html

https://www.cnblogs.com/xgqfrms/p/10896992.html

***

***
