### ISSUE TITLE
css & text-overflow: ellipsis;

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/CSS3#7]
# css & text-overflow: ellipsis;

https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

https://css-tricks.com/almanac/properties/t/text-overflow/

**Comment by xgqfrms** [comment]
https://www.cnblogs.com/xgqfrms/p/10259327.html

**Comment by xgqfrms** [comment]
# auto height & overflow: hidden; ???

> demo

https://codepen.io/xgqfrms/pen/EBmrLv

**Comment by xgqfrms** [comment]
# auto height & overflow: hidden;


```css
{overflow: hidden; height: 100%;} is the panacea!

{溢出：隐藏;身高：100％;}是灵丹妙药！

```

https://forum.textpattern.com/viewtopic.php?id=20059

https://stackoverflow.com/questions/9942026/can-i-use-overflowhidden-without-an-explicit-height-somehow

https://css-tricks.com/forums/topic/css-height-and-overflow/

https://css-tricks.com/almanac/properties/o/overflow/

# hack

> overflow: hidden;

1. 没有指定高度，永远不会溢出；
2. 高度是有内容自动撑出来的

https://css-tricks.com/almanac/properties/o/overflow/#article-header-id-2

![image](https://user-images.githubusercontent.com/7291672/60000347-96286000-9696-11e9-8d12-1400cea15949.png)

**Comment by xgqfrms** [comment]
https://www.cnblogs.com/xgqfrms/p/11077477.html

**Comment by xgqfrms** [comment]
```css
.labels-items-box{
    width: 50vw;
    /* height: auto; */
    min-height: 100px;
    /* min-height: 50px; */
    border: 1px solid red;
    margin: 50px auto;
    overflow: hidden;
}
 
/* overflow: hidden; ??? */
 
.label-item{
    float: left;
    display: block;
    min-width: 50px;
    /* width: auto; */
    max-width: 100px;
    background: #ccc;
    margin: 3px;
    padding: 5px;
    height: 20px;
    line-height: 20px;
    text-align: center;
    /* vertical-align: middle; */
    text-overflow: ellipsis;
    /* word-wrap: break-word; */
    white-space: nowrap;
    overflow: hidden;
}

```
