### ISSUE TITLE
CSS3 & Emoji & Animation & SVG

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/CSS3#9]
# CSS3 & Emoji & Animation & SVG

https://www.zhangxinxu.com/wordpress/2019/08/css-no-external-link/

![image](https://user-images.githubusercontent.com/7291672/64323499-33890400-cff7-11e9-9e93-7f54072b07c8.png)

**Comment by xgqfrms** [comment]
# css emoji

![image](https://user-images.githubusercontent.com/7291672/64308851-4b4b9280-cfcd-11e9-9209-2c5d4e11aa19.png)

https://my.chsi.com.cn/archive/index.action

```html
<div class="emoji-warp emoji-checked">
    <div data-name="非常符合" class="emoji emoji-7">
        <div class="face">
            <span class="eyes">
                <span class="eye"></span>
                <span class="eye"></span
            </span>
            <span class="mouth"></span>
        </div>
    </div>
</div>
```

```css


.one-topic .emoji-warp {
    height: 100px;
    width: 100px;
    margin-right: 43px;
    display: inline-block;
    position: relative
}

.one-topic .emoji-warp:last-child {
    margin-right: 0
}

.one-topic .emoji-checked .emoji .face {
    background: #f2dd68
}

.one-topic .emoji-checked .emoji .eye {
    background: #995710
}

.one-topic .emoji-checked .emoji .eye:before {
    background: #995710 !important
}

.one-topic .emoji-checked .emoji .mouth {
    background: #995710 !important
}

.one-topic .emoji-checked .emoji .mouth:after {
    background: #d9a827 !important
}

.one-topic .emoji-checked .emoji.emoji-3 .mouth,.one-topic .emoji-checked .emoji.emoji-5 .mouth {
    background: #f2dd68 !important;
    border-color: #995710
}

.one-topic .emoji-checked .emoji:after {
    color: #d9a827 !important
}

.one-topic .emoji {
    box-sizing: border-box;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%)
}

.one-topic .emoji:hover {
    cursor: pointer
}

.one-topic .emoji:hover .eye {
    animation-name: one-blink;
    animation-iteration-count: infinite;
    animation-duration: 2s
}

.one-topic .emoji:after {
    content: attr(data-name);
    display: block;
    color: #666;
    font-size: 16px;
    text-align: center;
    line-height: 16px;
    height: 16px;
    width: 100%;
    white-space: nowrap
}

.one-topic .emoji .face {
    width: 100px;
    height: 100px;
    position: relative;
    border-radius: 50%;
    background: #cdcdcd;
    margin: 10px auto
}

.one-topic .emoji .eye {
    position: absolute;
    width: 11px;
    height: 11px;
    top: 32px;
    left: 16px;
    z-index: 1;
    border-radius: 50%;
    background: #7e7e7e;
    transition: all .3s ease-in-out
}

.one-topic .emoji .eye:last-child {
    left: auto;
    right: 16px
}

.one-topic .emoji .mouth {
    position: absolute;
    top: 52px;
    left: 0;
    right: 0;
    z-index: 1;
    width: 70px;
    height: 34px;
    margin: 0 auto;
    border-radius: 0 0 70px 70px;
    overflow: hidden;
    background: #7e7e7e
}

.one-topic .emoji .mouth:before,.one-topic .emoji .mouth:after {
    content: '';
    position: absolute;
    display: block
}

.one-topic .emoji.emoji-7:hover .eye {
    animation: none;
    height: 11px;
    top: 32px
}

.one-topic .emoji.emoji-7:hover .mouth {
    animation-name: giggle;
    animation-iteration-count: infinite;
    animation-duration: .2s
}

.one-topic .emoji.emoji-7 .mouth:before {
    width: 100%;
    height: 10px;
    z-index: 2;
    background: #fffae6
}

.one-topic .emoji.emoji-7 .mouth:after {
    position: absolute;
    width: 38px;
    height: 38px;
    left: 0;
    right: 0;
    top: 15px;
    margin: 0 auto;
    border-radius: 50%;
    background: #9b9b9b
}

.one-topic .emoji.emoji-6 .mouth {
    height: 38px
}

.one-topic .emoji.emoji-6 .mouth:after {
    position: absolute;
    width: 38px;
    height: 38px;
    left: 0;
    right: 0;
    top: 15px;
    margin: 0 auto;
    border-radius: 50%;
    background: #9b9b9b
}

.one-topic .emoji.emoji-5 .mouth {
    width: 50px;
    height: 25px;
    background: transparent;
    border-radius: 0 0 50px 50px;
    border: 4px solid #7e7e7e;
    border-top: 0;
    clip-path: inset(30% 0 0 0)
}

.one-topic .emoji.emoji-4 .mouth {
    width: 60px;
    height: 4px;
    top: 65px;
    border-radius: 0
}

.one-topic .emoji.emoji-3 .mouth {
    width: 50px;
    height: 25px;
    top: 52px;
    background: transparent;
    border-radius: 50px 50px 0 0;
    border: 4px solid #7e7e7e;
    border-bottom: 0;
    clip-path: inset(0 0 30% 0)
}

.one-topic .emoji.emoji-F:hover .eye {
    animation: none;
    transform: scale(1.3, 1.3);
    transition: all 1.5s ease-out
}

.one-topic .emoji.emoji-F:hover .mouth {
    animation-name: wow;
    animation-iteration-count: infinite;
    animation-duration: 2.5s
}

.one-topic .emoji.emoji-F .mouth {
    width: 6px;
    height: 6px;
    background: #7e7e7e;
    border-radius: 50%
}

.one-topic .emoji.emoji-F .eye {
    transition: all .2s ease-in-out
}

.one-topic .emoji.emoji-2 .mouth {
    top: 44px;
    height: 34px;
    border-radius: 70px 70px 0 0
}

.one-topic .emoji.emoji-2 .mouth:after {
    position: absolute;
    width: 38px;
    height: 38px;
    left: 0;
    right: 0;
    top: 15px;
    margin: 0 auto;
    border-radius: 50%;
    background: #9b9b9b
}

.one-topic .emoji.emoji-1:hover .eye {
    animation-name: one-blink2
}

.one-topic .emoji.emoji-1 .mouth {
    width: 20px;
    height: 4px;
    top: 64px;
    border-radius: 0
}

.one-topic .emoji.emoji-1 .eye {
    top: 32px
}

.one-topic .emoji.emoji-1 .eye:before {
    content: '';
    display: block;
    position: absolute;
    width: 20px;
    height: 5px;
    top: -1px;
    left: -4px;
    background: #7e7e7e;
    transform: rotate(20deg)
}

.one-topic .emoji.emoji-1 .eye:last-child:before {
    left: auto;
    right: -4px;
    transform: rotate(-20deg)
}

.more-topic .emoji-warp {
    height: 100%;
    width: 100%;
    position: absolute;
    top: 0;
    left: 0;
}

.more-topic .emoji-warp:hover {
    background: #fff;
    border: 1px solid #ccc;
    height: 70px;
    width: 110%;
    top: 50%;
    margin-top: -35px;
    left: -6%;
    z-index: 99;
    box-shadow: 0 0 5px #ccc
}

.more-topic .emoji-warp:hover .emoji {
    top: 20%;
    transform: translate(-50%, -20%)
}

.more-topic .emoji-warp:hover .emoji:after {
    content: attr(data-name);
    display: block;
    color: #666;
    font-size: 12px;
    text-align: center;
    line-height: 12px;
    height: 12px;
    width: 100%;
    white-space: nowrap
}

.more-topic .emoji-checked .emoji .face {
    background: #f2dd68
}

.more-topic .emoji-checked .emoji .eye {
    background: #995710
}

.more-topic .emoji-checked .emoji .eye:before {
    background: #995710 !important
}

.more-topic .emoji-checked .emoji .mouth {
    background: #995710 !important
}

.more-topic .emoji-checked .emoji .mouth:after {
    background: #d9a827 !important;
}

.more-topic .emoji-checked .emoji.emoji-3 .mouth,.more-topic .emoji-checked .emoji.emoji-5 .mouth {
    background: #f2dd68 !important;
    border-color: #995710
}

.more-topic .emoji-checked .emoji:after {
    color: #d9a827 !important
}

.more-topic .emoji {
    box-sizing: border-box;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%)
}

.more-topic .emoji:hover .eye {
    animation-name: blink;
    animation-iteration-count: infinite;
    animation-duration: 2s
}

.more-topic .emoji .face {
    width: 30px;
    height: 30px;
    position: relative;
    border-radius: 50%;
    background: #cdcdcd;
    margin: 10px auto
}

.more-topic .emoji .eye {
    position: absolute;
    width: 3px;
    height: 3px;
    top: 8px;
    left: 7px;
    z-index: 1;
    border-radius: 50%;
    background: #7e7e7e;
    transition: all .3s ease-in-out
}

.more-topic .emoji .eye:last-child {
    left: auto;
    right: 7px
}

.more-topic .emoji .mouth {
    position: absolute;
    top: 16px;
    left: 0;
    right: 0;
    z-index: 1;
    width: 18px;
    height: 10px;
    margin: 0 auto;
    border-radius: 0 0 18px 18px;
    overflow: hidden;
    background: #7e7e7e
}

.more-topic .emoji .mouth:before,.more-topic .emoji .mouth:after {
    content: '';
    position: absolute;
    display: block
}

.more-topic .emoji.emoji-7:hover .eye {
    animation: none;
    height: 2px;
    top: 8px
}

.more-topic .emoji.emoji-7:hover .mouth {
    animation-name: giggle;
    animation-iteration-count: infinite;
    animation-duration: .2s
}

.more-topic .emoji.emoji-7 .mouth:before {
    width: 100%;
    height: 3px;
    z-index: 2;
    background: #e85759;
}

.more-topic .emoji.emoji-7 .mouth:after {
    position: absolute;
    width: 19px;
    height: 19px;
    left: 0;
    right: 0;
    top: 8px;
    margin: 0 auto;
    border-radius: 50%;
    background: #9b9b9b;
}

.more-topic .emoji.emoji-6 .mouth {
    height: 9px
}

.more-topic .emoji.emoji-6 .mouth:after {
    position: absolute;
    width: 9px;
    height: 9px;
    left: 0;
    right: 0;
    top: 4px;
    margin: 0 auto;
    border-radius: 50%;
    background: #9b9b9b
}

.more-topic .emoji.emoji-5 .mouth {
    width: 10px;
    height: 4px;
    background: transparent;
    border-radius: 0 0 10px 10px;
    border: 2px solid #7e7e7e;
    border-top: 0;
    clip-path: inset(30% 0 0 0)
}

.more-topic .emoji.emoji-4 .mouth {
    width: 10px;
    height: 2px;
    top: 18px;
    border-radius: 0
}

.more-topic .emoji.emoji-3 .mouth {
    width: 10px;
    height: 4px;
    top: 17px;
    background: transparent;
    border-radius: 10px 10px 0 0;
    border: 2px solid #7e7e7e;
    border-bottom: 0;
    clip-path: inset(0 0 30% 0)
}

.more-topic .emoji.emoji-F:hover .eye {
    animation: none;
    transform: scale(1.3, 1.3);
    transition: all 1.5s ease-out
}

.more-topic .emoji.emoji-F:hover .mouth {
    animation-name: wow;
    animation-iteration-count: infinite;
    animation-duration: 2.5s
}

.more-topic .emoji.emoji-F .mouth {
    width: 6px;
    height: 6px;
    background: #7e7e7e;
    border-radius: 50%
}

.more-topic .emoji.emoji-F .eye {
    transition: all .2s ease-in-out
}

.more-topic .emoji.emoji-2 .mouth {
    top: 14px;
    height: 9px;
    border-radius: 18px 18px 0 0
}

.more-topic .emoji.emoji-2 .mouth:after {
    position: absolute;
    width: 9px;
    height: 9px;
    left: 0;
    right: 0;
    top: 6px;
    margin: 0 auto;
    border-radius: 50%;
    background: #9b9b9b
}

.more-topic .emoji.emoji-1:hover .eye {
    animation-name: blink2
}

.more-topic .emoji.emoji-1 .mouth {
    width: 8px;
    height: 2px;
    top: 20px;
    border-radius: 0
}

.more-topic .emoji.emoji-1 .eye {
    top: 10px
}

.more-topic .emoji.emoji-1 .eye:before {
    content: '';
    display: block;
    position: absolute;
    width: 7px;
    height: 2px;
    top: -2px;
    left: -1px;
    background: #7e7e7e;
    transform: rotate(20deg)
}

.more-topic .emoji.emoji-1 .eye:last-child:before {
    left: auto;
    right: -1px;
    transform: rotate(-20deg)
}


```

**Comment by xgqfrms** [comment]
# css sparkle

![image](https://user-images.githubusercontent.com/7291672/64309572-8a7ae300-cfcf-11e9-82bb-7e5df5ac2847.png)

```html

<div class="TopicVoteCheckbox TopicVoteCheckbox--recommend VotableTopicCard-VoteCheckbox" data-tooltip="推荐"><input id="topic-recommend" type="checkbox"><label for="topic-recommend"><svg class="Zi Zi--Like" fill="currentColor" viewBox="0 0 24 24" width="19" height="19"><path d="M14.445 9h5.387s2.997.154 1.95 3.669c-.168.51-2.346 6.911-2.346 6.911s-.763 1.416-2.86 1.416H8.989c-1.498 0-2.005-.896-1.989-2v-7.998c0-.987.336-2.032 1.114-2.639 4.45-3.773 3.436-4.597 4.45-5.83.985-1.13 3.2-.5 3.037 2.362C15.201 7.397 14.445 9 14.445 9zM3 9h2a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V10a1 1 0 0 1 1-1z" fill-rule="evenodd"></path></svg><div class="TopicVoteCheckbox-Sparkle"></div><div class="TopicVoteCheckbox-Sparkle"></div><div class="TopicVoteCheckbox-Sparkle"></div><div class="TopicVoteCheckbox-Sparkle"></div><div class="TopicVoteCheckbox-Sparkle"></div><div class="TopicVoteCheckbox-Sparkle"></div><div class="TopicVoteCheckbox-Sparkle"></div><div class="TopicVoteCheckbox-Sparkle"></div></label></div>

```

```css

@-webkit-keyframes sparkle {
    50% {
        opacity: 1;
        -webkit-transform: scale(2.5);
        transform: scale(2.5)
    }

    to {
        -webkit-transform: scale(.6);
        transform: scale(.6);
        top: -5px
    }
}

@keyframes sparkle {
    50% {
        opacity: 1;
        -webkit-transform: scale(2.5);
        transform: scale(2.5)
    }

    to {
        -webkit-transform: scale(.6);
        transform: scale(.6);
        top: -5px
    }
}

.TopicVoteCheckbox--recommend .Zi {
    margin-top: -1px;
    width: 20px;
    height: 20px
}

.TopicVoteCheckbox--recommend>input:checked+label {
    background-color: #0084ff
}

html[data-theme=dark] .TopicVoteCheckbox--recommend>input:checked+label {
    background-color: #3a76d0
}

.TopicVoteCheckbox-Sparkle {
    position: absolute;
    top: 0;
    left: 0;
    width: 40px;
    height: 40px;
    border-radius: 50%
}

.TopicVoteCheckbox-Sparkle:before {
    content: "";
    position: absolute;
    top: 0;
    left: 50%;
    margin-left: -1px;
    width: 2px;
    height: 2px;
    background-color: #0084ff;
    border-radius: 50%;
    opacity: 0
}

html[data-theme=dark] .TopicVoteCheckbox-Sparkle:before {
    background-color: #3a76d0
}

.TopicVoteCheckbox--recommend>input:checked+label .TopicVoteCheckbox-Sparkle:before {
    -webkit-animation: sparkle .6s ease-in-out;
    animation: sparkle .6s ease-in-out;
    -webkit-animation-delay: .2s;
    animation-delay: .2s
}

.TopicVoteCheckbox-Sparkle:nth-child(2) {
    -webkit-transform: rotate(45deg);
    transform: rotate(45deg)
}

.TopicVoteCheckbox-Sparkle:nth-child(3) {
    -webkit-transform: rotate(90deg);
    transform: rotate(90deg)
}

.TopicVoteCheckbox-Sparkle:nth-child(4) {
    -webkit-transform: rotate(135deg);
    transform: rotate(135deg)
}

.TopicVoteCheckbox-Sparkle:nth-child(5) {
    -webkit-transform: rotate(180deg);
    transform: rotate(180deg)
}

.TopicVoteCheckbox-Sparkle:nth-child(6) {
    -webkit-transform: rotate(-45deg);
    transform: rotate(-45deg)
}

.TopicVoteCheckbox-Sparkle:nth-child(7) {
    -webkit-transform: rotate(-90deg);
    transform: rotate(-90deg)
}

.TopicVoteCheckbox-Sparkle:nth-child(8) {
    -webkit-transform: rotate(-135deg);
    transform: rotate(-135deg)
}

.TopicVoteCheckbox--against .Zi {
    margin-top: -1px;
    width: 20px;
    height: 20px
}

.TopicVoteCheckbox--against>input+label {
    -webkit-transform: rotate(180deg);
    transform: rotate(180deg)
}

.TopicVoteCheckbox--against>input:checked+label {
    background-color: #646464
}

html[data-theme=dark] .TopicVoteCheckbox--against>input:checked+label {
    background-color: #999
}

@-webkit-keyframes heart {
    0% {
        -webkit-transform: scale(1);
        transform: scale(1)
    }

    40% {
        -webkit-transform: scale(1.2);
        transform: scale(1.2)
    }

    70% {
        -webkit-transform: scale(1);
        transform: scale(1)
    }

    90% {
        -webkit-transform: scale(1.05);
        transform: scale(1.05)
    }

    to {
        -webkit-transform: scale(1);
        transform: scale(1)
    }
}

@keyframes heart {
    0% {
        -webkit-transform: scale(1);
        transform: scale(1)
    }

    40% {
        -webkit-transform: scale(1.2);
        transform: scale(1.2)
    }

    70% {
        -webkit-transform: scale(1);
        transform: scale(1)
    }

    90% {
        -webkit-transform: scale(1.05);
        transform: scale(1.05)
    }

    to {
        -webkit-transform: scale(1);
        transform: scale(1)
    }
}

@-webkit-keyframes pop {
    to {
        -webkit-transform: scale(1);
        transform: scale(1)
    }
}

@keyframes pop {
    to {
        -webkit-transform: scale(1);
        transform: scale(1)
    }
}

.TopicVoteCheckbox {
    display: inline-block;
    width: 40px;
    height: 40px
}

.TopicVoteCheckbox>input {
    position: absolute;
    left: -100vw
}

.TopicVoteCheckbox>input+label {
    z-index: 1;
    cursor: pointer;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    justify-content: center;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    width: 40px;
    height: 40px;
    position: relative;
    border-radius: 50%;
    color: #8590a6;
    background: #fff;
    border: .5px solid #ebebeb;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    -webkit-transition: background-color .5s;
    transition: background-color .5s
}

html[data-theme=dark] .TopicVoteCheckbox>input+label {
    color: #606a80;
    background: #1a1a1a;
    border: .5px solid #444
}

.TopicVoteCheckbox>input+label:before {
    width: 40px;
    height: 40px;
    margin: -20px;
    position: absolute;
    top: 50%;
    left: 50%;
    border-radius: 50%;
    content: "";
    background: #fff;
    opacity: .2;
    z-index: 0;
    -webkit-transform: scale(0);
    transform: scale(0)
}

html[data-theme=dark] .TopicVoteCheckbox>input+label:before {
    background: #1a1a1a
}

.TopicVoteCheckbox>input:checked+label {
    color: #fff;
    border: 0
}

html[data-theme=dark] .TopicVoteCheckbox>input:checked+label {
    color: #1a1a1a
}

.TopicVoteCheckbox>input:checked+label>.Zi {
    -webkit-animation: heart .5s ease-in-out;
    animation: heart .5s ease-in-out;
    -webkit-animation-delay: .5s;
    animation-delay: .5s
}

.TopicVoteCheckbox>input:checked+label:before {
    -webkit-animation: pop .5s ease-in-out;
    animation: pop .5s ease-in-out
}

.VotableTopicCard {
    background-color: #f6f6f6;
    padding: 10px 15px 10px 12px;
    border-radius: 8px;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: horizontal;
    -webkit-box-direction: normal;
    -ms-flex-direction: row;
    flex-direction: row;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center
}

html[data-theme=dark] .VotableTopicCard {
    background-color: #2e2e2e
}

.VotableTopicCard-VoteCheckbox {
    vertical-align: top
}

.VotableTopicCard-VoteCheckbox+.VotableTopicCard-VoteCheckbox {
    margin-left: 9px
}

.VotableTopicCard-RecommendStatus {
    display: -webkit-inline-box;
    display: -ms-inline-flexbox;
    display: inline-flex;
    margin: auto;
    -webkit-box-pack: justify;
    -ms-flex-pack: justify;
    justify-content: space-between
}

.VotableTopicCard-VoteActions--noAnimation *,.VotableTopicCard-VoteActions--noAnimation :after,.VotableTopicCard-VoteActions--noAnimation :before {
    -webkit-animation: unset!important;
    animation: unset!important;
    -webkit-transition: unset!important;
    transition: unset!important
}

.QuestionHeaderTopicMeta {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    height: 74px;
    -webkit-box-pack: justify;
    -ms-flex-pack: justify;
    justify-content: space-between;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    padding: 0 12px;
    background-color: #f6f6f6;
    margin-top: 14px
}

html[data-theme=dark] .QuestionHeaderTopicMeta {
    background-color: #2e2e2e
}

.QuestionHeaderTopicMeta.Card {
    margin-bottom: 14px;
    -webkit-box-shadow: none;
    box-shadow: none;
    border: 1px solid #ebebeb
}

html[data-theme=dark] .QuestionHeaderTopicMeta.Card {
    border: 1px solid #444
}

.QuestionHeaderTopicMeta-Content {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -ms-flex-direction: column;
    flex-direction: column;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    height: 48px;
    margin: 1px 0;
    padding: 1px 0;
    -webkit-box-pack: justify;
    -ms-flex-pack: justify;
    justify-content: space-between
}

.QuestionHeaderTopicMeta-CardMain {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    margin-top: 2px
}

.QuestionHeaderTopicMeta-SideImg {
    width: 36px;
    height: 54px
}

.QuestionHeaderTopicMeta-SideImg--goods {
    width: 54px
}

.QuestionHeaderTopicMeta-Info {
    margin-left: 10px;
    color: #999;
    max-width: 469px;
    height: 20px;
    display: -webkit-box;
    text-overflow: ellipsis;
    overflow: hidden;
    -webkit-line-clamp: 1;
    -webkit-box-orient: vertical
}

html[data-theme=dark] .QuestionHeaderTopicMeta-Info {
    color: #646464
}

.QuestionHeaderTopicMeta-CardTitleContainer {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    margin-bottom: 7px;
    margin-left: 10px;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center
}

.QuestionHeaderTopicMeta-VoteInfo {
    color: #444;
    margin-left: 14px;
    position: relative
}

html[data-theme=dark] .QuestionHeaderTopicMeta-VoteInfo {
    color: grey
}

.QuestionHeaderTopicMeta-VoteInfo:nth-child(2) {
    margin-left: 7px
}

.QuestionHeaderTopicMeta-VoteInfo:nth-child(3):before {
    content: "";
    position: absolute;
    width: 2px;
    left: -7px;
    background-color: #444;
    top: 50%;
    -webkit-transform: translateY(-50%);
    transform: translateY(-50%);
    height: 2px;
    border-radius: 50%
}

html[data-theme=dark] .QuestionHeaderTopicMeta-VoteInfo:nth-child(3):before {
    background-color: grey
}

.QuestionHeaderTopicMeta .VotableTopicCard {
    height: 100%;
    padding-top: 5px
}

```


https://www.zhihu.com/question/20833983
